export function generateMarkdown(plan: any) {
  let md = `# ${plan.plan_title}\n\n`;
  md += `**Mission:** ${plan.plan_description}\n\n`;
  
  md += `## Tool Stack\n`;
  plan.tool_stack.forEach((t: any) => {
    md += `- **${t.tool_name}** (${t.output_type}): ${t.use_case}\n`;
  });
  md += `\n`;

  md += `## Execution Steps\n`;
  plan.steps.forEach((step: any) => {
    md += `### Step ${step.step_number}: ${step.title}\n`;
    md += `**Tool:** ${step.tool_used}\n\n`;
    md += `**Objective:** ${step.instruction}\n\n`;
    md += "```text\n" + step.prompt + "\n```\n\n";
    if (step.troubleshooting_tip) {
      md += `> **Tip:** ${step.troubleshooting_tip}\n\n`;
    }
  });

  if (plan.other_information) {
    md += `## Notes\n${plan.other_information}\n`;
  }

  return md;
}

export function generateHTML(plan: any) {
  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${plan.plan_title} - Launch Plan</title>
  <style>
    body { font-family: system-ui, -apple-system, sans-serif; line-height: 1.6; color: #e4e4e7; background: #09090b; max-width: 800px; margin: 0 auto; padding: 40px 20px; }
    h1 { color: #fff; font-size: 2.5rem; margin-bottom: 0.5rem; }
    h2 { color: #a78bfa; margin-top: 2rem; border-bottom: 1px solid #27272a; padding-bottom: 0.5rem; }
    h3 { color: #fff; margin-top: 1.5rem; }
    .mission { color: #a1a1aa; font-size: 1.1rem; margin-bottom: 2rem; }
    .tool-stack { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1rem; margin-bottom: 2rem; }
    .tool-card { background: #18181b; padding: 1rem; border-radius: 0.5rem; border: 1px solid #27272a; }
    .tool-name { font-weight: bold; color: #fff; }
    .tool-meta { font-size: 0.8rem; color: #71717a; text-transform: uppercase; letter-spacing: 0.05em; }
    .step { background: #18181b; border: 1px solid #27272a; border-radius: 0.75rem; padding: 1.5rem; margin-bottom: 1.5rem; }
    .step-header { display: flex; align-items: center; gap: 1rem; margin-bottom: 1rem; }
    .step-num { background: #27272a; color: #fff; width: 2rem; height: 2rem; display: flex; align-items: center; justify-content: center; border-radius: 99px; font-weight: bold; font-family: monospace; }
    .step-tool { color: #a78bfa; font-size: 0.9rem; font-weight: bold; }
    pre { background: #000; padding: 1rem; border-radius: 0.5rem; overflow-x: auto; border: 1px solid #27272a; color: #d4d4d8; }
    .tip { background: #1e1b4b; border-left: 4px solid #6366f1; padding: 1rem; margin-top: 1rem; color: #c7d2fe; font-size: 0.9rem; }
  </style>
</head>
<body>
  <h1>${plan.plan_title}</h1>
  <p class="mission">${plan.plan_description}</p>

  <h2>Tool Stack</h2>
  <div class="tool-stack">
    ${plan.tool_stack.map((t: any) => `
      <div class="tool-card">
        <div class="tool-name">${t.tool_name}</div>
        <div class="tool-meta">${t.output_type}</div>
        <div style="font-size: 0.9rem; margin-top: 0.5rem;">${t.use_case}</div>
      </div>
    `).join('')}
  </div>

  <h2>Execution Steps</h2>
  ${plan.steps.map((step: any) => `
    <div class="step">
      <div class="step-header">
        <div class="step-num">${step.step_number}</div>
        <div>
          <h3 style="margin:0">${step.title}</h3>
          <div class="step-tool">Using ${step.tool_used}</div>
        </div>
      </div>
      <p><strong>Objective:</strong> ${step.instruction}</p>
      <pre>${step.prompt}</pre>
      ${step.troubleshooting_tip ? `<div class="tip"><strong>Pro Tip:</strong> ${step.troubleshooting_tip}</div>` : ''}
    </div>
  `).join('')}

  ${plan.other_information ? `<h2>Architect's Notes</h2><p>${plan.other_information}</p>` : ''}
  
  <footer style="margin-top: 4rem; text-align: center; color: #52525b; font-size: 0.8rem;">
    Generated by WhiteInputSyndrome
  </footer>
</body>
</html>
  `;
}

export function generateJSON(plan: any) {
  return JSON.stringify(plan, null, 2);
}

export function downloadFile(content: string, filename: string, type: string) {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

